In [146]:
from imageTools import *
import pandas as pd
#import matplotlib.pyplot as plt

## Image params ##

nu = 2030
nv = 34

im = Image(nv,nu)
#dirPath = r'C:\Users\Vishal.Metri\Documents\MobaXterm\home\Work\Highres\bkt002\bkt002_fdk_goodreso'
#dirPath = r'C:\Users\Vishal.Metri\Documents\MobaXterm\home\Work\Highres\cwp1\cwp1_fdk_goodreso'
dirPath = r'C:\Users\Vishal.Metri\Documents\MobaXterm\home\Work\Highres\rha02_new\ring_proj'
fmt = 'single'
################

## Load image ##
imPath = dirPath + '\\' + 'exp_proj_filtered2.raw'
#imPath = dirPath + '\\' + 'cudaCorrReso_bkt002_z1027_2032x2032x1.raw'
#imPath = dirPath + '\\' + 'sliceMLEM350.raw'
im.readFromFile2D(imPath,fmt)
################

## Smaller image ##
im2 = Image(nv,17)

## Left profile ##
im2.data = im.data[:,0:17]
lineLims = np.array([[0,(nv*.5 - 1),14,(nv*.5 - 1)]])

## Right profile ##
#im2.data = im.data[:,(nu - 17):nu]
#lineLims = np.array([[2,(nv*.5 - 1),16,(nv*.5 - 1)]])

#print(lineLims)
#lineLims = lineLims.to_numpy()
#print(lineLims)

## Process lineLims ##
s = np.shape(lineLims)
numRegions = s[0]
print(numRegions)

## Initialize output list ##
lp = []
###################################

%matplotlib qt
fig1 = plt.figure(figsize=(3, 5), dpi=100)
drawOptions = {'color':'red','linewidth' : 1.5}

#fig2, ax = plt.subplots(nrows=2, ncols=2, figsize=(8, 8), dpi=100)
#print(ax)

for i in range(numRegions):
    x1 = lineLims[i,0]
    y1 = lineLims[i,1]
    x2 = lineLims[i,2]
    y2 = lineLims[i,3]
    
    p1 = Point(x1,y1)
    p2 = Point(x2,y2)

    lp1 = LinePlot(im2,p1,p2)
    lp1.getLineProfile()
    #plt.subplot(2,2,i + 1)
    #plt.plot(lp1.lpdata)
    lp1.drawLine(drawOptions)
    
    
    #lp1.getLineProfile()
    #lp.append(lp1.lpdata)

#fig1 = plt.figure(figsize=(10, 10), dpi=100)
#drawOptions = {'color':'red','linewidth' : 1}
plt.imshow(im2.data, cmap='gray')

plt.xlabel('Left pixels',fontsize = 14)
plt.ylabel('Vertical pixels', fontsize = 14)
plt.tight_layout()


#plt.imshow(im.data[:,(nu - 15):(nu)], cmap='gray')
#lp1.drawLine(drawOptions)
plt.show()

fig2 = plt.figure(figsize=(5, 5), dpi=100)
plt.plot(lp1.lpdata)
plt.xlabel('Left pixels', fontsize = 14)
plt.ylabel('Pixel value', fontsize = 14)
plt.tight_layout()
#plt.tight_layout(rect = (0.123,0.123,0.97,0.97))

#df0 = pd.DataFrame(lp)
#df0 = df0.T
#print(df0.iloc[:,0])
#df0.to_excel("output_rha_fdk.xlsx")

#with pd.ExcelWriter('output2.xlsx',engine='openpyxl',mode='a') as writer:
#    df0.to_excel(writer,sheet_name='sn2')
#    df0.to_excel(writer,sheet_name='sn3')


#p1 = [x1,x2]
#p2 = [y1,y2]
#plt.plot(p1,p2,color="red", linewidth=2)


#######

#fig2 = plt.figure(figsize=(8, 8), dpi=100)
#plt.plot(finData[:,3])
#plt.plot(lp1.lpdata)

#fig1.savefig('save1.tif',dpi=300)

1


C:\Users\Vishal.Metri\Documents\MobaXterm\home\Work\Code\Python\imageTools.py:44: FutureWarning: Default out of bounds interpolation mode 'constant' is deprecated. In version 0.19 it will be set to 'reflect'. To avoid this warning, set `mode=` explicitly.
  self.lpdata = measure.profile_line(self.imData,(y1,x1),(y2,x2))


In [7]:
# import matplotlib.pyplot as plt
from imageTools import *
from skimage import measure
import pandas as pd



In [71]:
z = [1,2,3,4,5]
print(z[1:len(z)])

[2, 3, 4, 5]


In [99]:
z = np.array([[1,2,3],[4,5,6]])
print(z.T)
c = np.array([[7,8,9]])
#print(np.shape(z.T))
print(np.shape(c))
z2 = np.concatenate((z,c), axis = 0)
print(z2)

[[1 4]
 [2 5]
 [3 6]]
(1, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
l1 = {'color':'red','linewidth' : 2}
print(l1['linewidth'])

2


In [4]:
a = list(range(0,1001,50))
print(a)

[0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000]


In [24]:
np.sqrt((576 - 432.0)**2 + (950 - 52)**2 + (144)**2)

920.8018244986268

In [11]:
x = dict()
x['zing'] = 1.0
x['bing'] = 'zelda'
x['yoda'] = np.array([4])

z = pd.DataFrame(data=x)
print(z)
print(x)

   zing   bing  yoda
0   1.0  zelda     4
{'zing': 1.0, 'bing': 'zelda', 'yoda': array([4])}


In [5]:
z = np.array([[1,2,3],[4,5,6]])
print(z)

[[1 2 3]
 [4 5 6]]
