In [1]:
from imageTools import *
import pandas as pd

# This notebook provides line profiles for a set of files. Eg: For iterative algos, we need to 
# plot the line profiles as a function of iteration number. For this, we choose one of the images
# and identify a few line profiles. These line limits are the input, and are stored in an excel
# Input: 
# lineProfFile: This is an excel sheet with x-y limits of the end points of the line
# dirPath: The path of the lineProfFile and images
# imX, imY: Image dimensions
# fmt: Image format
# outFile: Excel file of the line profiles for all image files. This number of sheets are equal to the number of 
# line profiles. In each sheet, the line profile data for all files are written column-wise for a given line, for all
# the files.


## Set directory and image params ##
#dirPath = r'C:\Users\Vishal.Metri\Documents\MobaXterm\home\Work\Highres\rha02_new\mlemIterTest\rha02_mlemSlices'
dirPath = r'C:\Users\Vishal.Metri\Documents\MobaXterm\home\Work\Highres\bkt002\mlemIterTest\bkt002_mlemSlices'

imX = imY = 2032
lineProfFile = 'lineProfs_bkt002.xlsx'
fmt = 'single'

outFile = 'bkt002_MLEM_LineProfiles.xlsx'
outPath = dirPath + '\\' + outFile
###################################

## Read line limits for profiles ##
lpFilePath = dirPath + '\\' + lineProfFile
lineLims = pd.read_excel(lpFilePath)
lineLims = lineLims.to_numpy()
print(lineLims)
###################################

## Set iteration(file) numbers ##
startIter = 50
endIter = 350
iterStep = 50  # Iteration step
numFiles = (endIter - startIter)/iterStep + 1
############################

## Get number of line profiles ##
siz = np.shape(lineLims)
numProfiles = siz[0]
print(numProfiles)
###################################


for i in range(int(numFiles)):
    fNum = startIter + i*iterStep
    fName = 'sliceMLEM' + str(fNum) + '.raw'
    lp = getLineProfiles(dirPath, fName, imX, imY, fmt, lineLims)
    df1 = pd.DataFrame(lp)
    print("Initial shape is ",df1.shape)
    
    if (i == 0):
        df = df1.T
    else:
        df = pd.concat([df, df1.T], axis = 1)

print(df.shape)
#df.to_excel('Full.xlsx')

for i in range(numProfiles):
    sheetName = 'LineProfile ' + str(i)
    d1 = []
    for j in range(int(numFiles)):
        colNum = i + j*numProfiles
        print("Column is ",colNum)
        d1.append(df.iloc[:,colNum])
        
    df2 = pd.DataFrame(d1)
    print("df2 shape is ",df2.shape)
    df2 = df2.T
    
    if (i == 0):
        df2.to_excel(outPath,sheet_name = sheetName)
    else:
        with pd.ExcelWriter(outPath,engine='openpyxl',mode='a') as writer:
            df2.to_excel(writer,sheet_name=sheetName)
            


[[1131  358 1184  425]
 [1092  632 1034  698]
 [1421 1351 1505 1417]
 [1237 1150 1295 1206]]
4
[[1131  358 1184  425]
 [1092  632 1034  698]
 [1421 1351 1505 1417]
 [1237 1150 1295 1206]]
4
Initial shape is  (4, 108)
[[1131  358 1184  425]
 [1092  632 1034  698]
 [1421 1351 1505 1417]
 [1237 1150 1295 1206]]
4
Initial shape is  (4, 108)
[[1131  358 1184  425]
 [1092  632 1034  698]
 [1421 1351 1505 1417]
 [1237 1150 1295 1206]]
4
Initial shape is  (4, 108)
[[1131  358 1184  425]
 [1092  632 1034  698]
 [1421 1351 1505 1417]
 [1237 1150 1295 1206]]
4
Initial shape is  (4, 108)
[[1131  358 1184  425]
 [1092  632 1034  698]
 [1421 1351 1505 1417]
 [1237 1150 1295 1206]]
4
Initial shape is  (4, 108)
[[1131  358 1184  425]
 [1092  632 1034  698]
 [1421 1351 1505 1417]
 [1237 1150 1295 1206]]
4
Initial shape is  (4, 108)
[[1131  358 1184  425]
 [1092  632 1034  698]
 [1421 1351 1505 1417]
 [1237 1150 1295 1206]]
4
Initial shape is  (4, 108)
(108, 28)
Column is  0
Column is  4
Column is  8
Co

C:\Users\Vishal.Metri\Documents\MobaXterm\home\Work\Code\Python\imageTools.py:35: FutureWarning: Default out of bounds interpolation mode 'constant' is deprecated. In version 0.19 it will be set to 'reflect'. To avoid this warning, set `mode=` explicitly.
  self.lpdata = measure.profile_line(self.imData,(y1,x1),(y2,x2))


df2 shape is  (7, 108)
Column is  1
Column is  5
Column is  9
Column is  13
Column is  17
Column is  21
Column is  25
df2 shape is  (7, 108)
Column is  2
Column is  6
Column is  10
Column is  14
Column is  18
Column is  22
Column is  26
df2 shape is  (7, 108)
Column is  3
Column is  7
Column is  11
Column is  15
Column is  19
Column is  23
Column is  27
df2 shape is  (7, 108)


In [ ]:
x = [[],[]]
print(x)
a = [1,2]
x[1].append(a)
print(x)
b = [3,4]
x[1].append(b)
print(x)

In [33]:
x = [[2,3]]
y = [[4,5]]
z = x + y
print(z)

[[2, 3], [4, 5]]


In [60]:
z = [[],[]]
fName = 'sliceMLEM500.raw'
lp = getLineProfiles(dirPath, fName, imX, imY, fmt, lineProfFile)
#a = [lp[0]]
a = np.array(lp[0])
print(np.shape(a))
z[0] = a
fName2 = 'sliceMLEM600.raw'
lp2 = getLineProfiles(dirPath, fName2, imX, imY, fmt, lineProfFile)
#b = [lp2[0]]
b = np.array(lp2[0])
print(np.shape(b))
z[1] = b

a = a + b
#print(a)

df0 = pd.DataFrame(z)
df0 = df0.T
df0.to_excel("test.xlsx")


[[1080 1590 1220 1515]
 [1080  590 1080  667]
 [ 958  256 1093  380]
 [1699  784 1707  923]]
4
(160,)
[[1080 1590 1220 1515]
 [1080  590 1080  667]
 [ 958  256 1093  380]
 [1699  784 1707  923]]
4
(160,)


In [ ]:
#print(z)

#df0 = pd.DataFrame(z)
#df0 = df0.T



#lp0 = lp[0]
#print(lp)
#np.array((lp))
#print(len(lp[1]))



#print(a)
#lp3 = lp[0].append(lp2[0])
#lp3 = np.concatenate((lp[0].T,lp2[0].T),axis = 1)
#print(lp3)
#np.array((lp2))
#print(np.shape(lp2))
#print(lp2)

#lp3 = np.concatenate((lp[0,:],lp2[0,:]),axis = 0)
#print(lp3)
#lp = lp.extend(lp2)


#print(lp2)
#print(len(lp2))